### ISSUE TITLE
nullptr exception in VESceneManager.cpp

### ISSUE THREAD

**Issue by Spliomix** [hlavacs/ViennaVulkanEngine#2]
in VulkanEngine\VESceneManager.cpp line 930
develop branch

after i used key "1" without creating an event listener for that key

**Comment by hlavacs** [comment]
main.cpp creates a LevelListener that waits for keys 1, 2, or 3, then deletes the scene and reloads it completely. Something must go wrong in one of these steps. I recommend to debug it and post where the crash happens.

**Comment by Spliomix** [comment]
Ok i think i found the problem.
If i use the same name for createSceneNode() and the createEntity(), this will happen
