### ISSUE TITLE
Window does not react to X button click

### ISSUE THREAD

**Issue by drepekh** [hlavacs/ViennaVulkanEngine#5]
There exists function `VEWindow::windowShouldClose()` that is not actually used in the `VEEngine` class and can't be used by the derived classes because of its protected modifier. Proposed solutions:

1.  Make `VEWindow::windowShouldClose()` public. Not the best option, because this way condition could be checked only during processing of some other event (e.g. `VE_EVENT_FRAME_STARTED`)
2. Create new event type that fires when `VEWindow::windowShouldClose()` becomes true.

**Comment by hlavacs** [comment]
Fixed
