### ISSUE TITLE
Clock resolution

### ISSUE THREAD

**Issue by drepekh** [hlavacs/ViennaVulkanEngine#8]
Is there any specific reason why you've decided to cast duration to milliseconds instead of directly returning `time_span` in this function?
```
float vhTimeDuration(std::chrono::high_resolution_clock::time_point t_prev) {
	std::chrono::duration<double> time_span =
		std::chrono::duration_cast<std::chrono::duration<double>>(vhTimeNow() - t_prev);
	return std::chrono::duration_cast<std::chrono::milliseconds>(time_span).count() / 1000.0f;
}
```
This function is used to calculate `dt` for events and I would assume that clock resolution of 1 millisecond is not good enough, which is  quite noticeable in cases when frame time is 1-2 ms, because truncation error can be as high as 50% in those cases.

**Comment by hlavacs** [comment]
Changed to microseconds
